/**
 * generated by Xtext 2.24.0
 */
package mArIoDSL.tests;

import com.google.inject.Inject;
import mArIoDSL.myDsl.Model;
import mArIoDSL.tests.MyDslInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;

/* @ExtendWith(InjectionExtension.class) */@InjectWith(MyDslInjectorProvider.class)
@SuppressWarnings("all")
public class MyDslParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;
  
  /* @Test
   */public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Assertions is undefined"
      + "\nThe method or field Assertions is undefined"
      + "\nassertNotNull cannot be resolved"
      + "\nassertTrue cannot be resolved");
  }
}
