/*
 * generated by Xtext 2.24.0
 */
package mArIoDSL;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
