/**
 * generated by Xtext 2.24.0
 */
package mArIoDSL.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mArIoDSL.myDsl.Item#getItemID <em>Item ID</em>}</li>
 *   <li>{@link mArIoDSL.myDsl.Item#getItemName <em>Item Name</em>}</li>
 *   <li>{@link mArIoDSL.myDsl.Item#getDescription <em>Description</em>}</li>
 *   <li>{@link mArIoDSL.myDsl.Item#getItemWeight <em>Item Weight</em>}</li>
 * </ul>
 *
 * @see mArIoDSL.myDsl.MyDslPackage#getItem()
 * @model
 * @generated
 */
public interface Item extends EObject
{
  /**
   * Returns the value of the '<em><b>Item ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item ID</em>' attribute.
   * @see #setItemID(String)
   * @see mArIoDSL.myDsl.MyDslPackage#getItem_ItemID()
   * @model
   * @generated
   */
  String getItemID();

  /**
   * Sets the value of the '{@link mArIoDSL.myDsl.Item#getItemID <em>Item ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Item ID</em>' attribute.
   * @see #getItemID()
   * @generated
   */
  void setItemID(String value);

  /**
   * Returns the value of the '<em><b>Item Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item Name</em>' attribute.
   * @see #setItemName(String)
   * @see mArIoDSL.myDsl.MyDslPackage#getItem_ItemName()
   * @model
   * @generated
   */
  String getItemName();

  /**
   * Sets the value of the '{@link mArIoDSL.myDsl.Item#getItemName <em>Item Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Item Name</em>' attribute.
   * @see #getItemName()
   * @generated
   */
  void setItemName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see mArIoDSL.myDsl.MyDslPackage#getItem_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link mArIoDSL.myDsl.Item#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Item Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item Weight</em>' attribute.
   * @see #setItemWeight(int)
   * @see mArIoDSL.myDsl.MyDslPackage#getItem_ItemWeight()
   * @model
   * @generated
   */
  int getItemWeight();

  /**
   * Sets the value of the '{@link mArIoDSL.myDsl.Item#getItemWeight <em>Item Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Item Weight</em>' attribute.
   * @see #getItemWeight()
   * @generated
   */
  void setItemWeight(int value);

} // Item
