/**
 * generated by Xtext 2.24.0
 */
package mArIoDSL.myDsl.impl;

import mArIoDSL.myDsl.Item;
import mArIoDSL.myDsl.MyDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Item</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mArIoDSL.myDsl.impl.ItemImpl#getItemID <em>Item ID</em>}</li>
 *   <li>{@link mArIoDSL.myDsl.impl.ItemImpl#getItemName <em>Item Name</em>}</li>
 *   <li>{@link mArIoDSL.myDsl.impl.ItemImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link mArIoDSL.myDsl.impl.ItemImpl#getItemWeight <em>Item Weight</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ItemImpl extends MinimalEObjectImpl.Container implements Item
{
  /**
   * The default value of the '{@link #getItemID() <em>Item ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItemID()
   * @generated
   * @ordered
   */
  protected static final String ITEM_ID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getItemID() <em>Item ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItemID()
   * @generated
   * @ordered
   */
  protected String itemID = ITEM_ID_EDEFAULT;

  /**
   * The default value of the '{@link #getItemName() <em>Item Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItemName()
   * @generated
   * @ordered
   */
  protected static final String ITEM_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getItemName() <em>Item Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItemName()
   * @generated
   * @ordered
   */
  protected String itemName = ITEM_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The default value of the '{@link #getItemWeight() <em>Item Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItemWeight()
   * @generated
   * @ordered
   */
  protected static final int ITEM_WEIGHT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getItemWeight() <em>Item Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItemWeight()
   * @generated
   * @ordered
   */
  protected int itemWeight = ITEM_WEIGHT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ITEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getItemID()
  {
    return itemID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setItemID(String newItemID)
  {
    String oldItemID = itemID;
    itemID = newItemID;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ITEM__ITEM_ID, oldItemID, itemID));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getItemName()
  {
    return itemName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setItemName(String newItemName)
  {
    String oldItemName = itemName;
    itemName = newItemName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ITEM__ITEM_NAME, oldItemName, itemName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ITEM__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getItemWeight()
  {
    return itemWeight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setItemWeight(int newItemWeight)
  {
    int oldItemWeight = itemWeight;
    itemWeight = newItemWeight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ITEM__ITEM_WEIGHT, oldItemWeight, itemWeight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ITEM__ITEM_ID:
        return getItemID();
      case MyDslPackage.ITEM__ITEM_NAME:
        return getItemName();
      case MyDslPackage.ITEM__DESCRIPTION:
        return getDescription();
      case MyDslPackage.ITEM__ITEM_WEIGHT:
        return getItemWeight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ITEM__ITEM_ID:
        setItemID((String)newValue);
        return;
      case MyDslPackage.ITEM__ITEM_NAME:
        setItemName((String)newValue);
        return;
      case MyDslPackage.ITEM__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case MyDslPackage.ITEM__ITEM_WEIGHT:
        setItemWeight((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ITEM__ITEM_ID:
        setItemID(ITEM_ID_EDEFAULT);
        return;
      case MyDslPackage.ITEM__ITEM_NAME:
        setItemName(ITEM_NAME_EDEFAULT);
        return;
      case MyDslPackage.ITEM__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case MyDslPackage.ITEM__ITEM_WEIGHT:
        setItemWeight(ITEM_WEIGHT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ITEM__ITEM_ID:
        return ITEM_ID_EDEFAULT == null ? itemID != null : !ITEM_ID_EDEFAULT.equals(itemID);
      case MyDslPackage.ITEM__ITEM_NAME:
        return ITEM_NAME_EDEFAULT == null ? itemName != null : !ITEM_NAME_EDEFAULT.equals(itemName);
      case MyDslPackage.ITEM__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case MyDslPackage.ITEM__ITEM_WEIGHT:
        return itemWeight != ITEM_WEIGHT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ItemID: ");
    result.append(itemID);
    result.append(", ItemName: ");
    result.append(itemName);
    result.append(", description: ");
    result.append(description);
    result.append(", ItemWeight: ");
    result.append(itemWeight);
    result.append(')');
    return result.toString();
  }

} //ItemImpl
