/*
 * generated by Xtext 2.24.0
 */
package mArIoDSL.ui.tests;

import com.google.inject.Injector;
import mArIoDSL.mydsl.ui.internal.MydslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("mArIoDSL.MyDsl");
	}

}
